inco_map = {"Inco-terms": {"Ex Works (EXW)": {"Export Packaging": "Seller", "Loading Charges": "Buyer",
                                             "Delivery to Port/Place": "Buyer",
                                             "Export Duty, Taxes and Customs Clearance": "Buyer",
                                             "Origin Handling Terminal Charges": "Buyer",
                                             "Loading on Carriage": "Buyer", "Freight Charges": "Buyer",
                                             "Insurance": "Buyer (Negotiable)", "Destination Terminal Handling Charges": "Buyer",
                                             "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                             "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Free Carrier (FCA)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                  "Delivery to Port/Place": "Seller",
                                                  "Export Duty, Taxes and Customs Clearance": "Seller",
                                                  "Origin Handling Terminal Charges": "Buyer",
                                                  "Loading on Carriage": "Buyer", "Freight Charges": "Buyer",
                                                  "Insurance": "Buyer (Negotiable)", "Destination Terminal Handling Charges": "Buyer",
                                                  "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                  "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Free Alongside Ship (FAS)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                         "Delivery to Port/Place": "Seller",
                                                         "Export Duty, Taxes and Customs Clearance": "Seller",
                                                         "Origin Handling Terminal Charges": "Seller",
                                                         "Loading on Carriage": "Buyer", "Freight Charges": "Buyer",
                                                         "Insurance": "Buyer (Negotiable)",
                                                         "Destination Terminal Handling Charges": "Buyer",
                                                         "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                         "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Free On Board (FOB)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Buyer",
                                                   "Insurance": "Buyer (Negotiable)", "Destination Terminal Handling Charges": "Buyer",
                                                   "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Cost and Freight (CFR)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                      "Delivery to Port/Place": "Seller",
                                                      "Export Duty, Taxes and Customs Clearance": "Seller",
                                                      "Origin Handling Terminal Charges": "Seller",
                                                      "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                      "Insurance": "Buyer (Negotiable)", "Destination Terminal Handling Charges": "Buyer",
                                                      "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                      "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Cost, Insurance and Freight (CIF)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller", "Destination Terminal Handling Charges": "Buyer",
                                                   "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Carriage Paid To (CPT)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller (Negotiable)", "Destination Terminal Handling Charges": "Seller",
                                                   "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Carriage and Insurance Paid To (CIP)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller", "Destination Terminal Handling Charges": "Seller",
                                                   "Delivery To Destination": "Buyer", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Delivered At Place (DAP)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller (Negotiable)", "Destination Terminal Handling Charges": "Seller",
                                                   "Delivery To Destination": "Seller", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Delivered At Place Unloaded (DPU)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller (Negotiable)", "Destination Terminal Handling Charges": "Seller",
                                                   "Delivery To Destination": "Seller", "Unloading At Destination": "Seller",
                                                   "Import Duty, Taxes and Customs Clearance": "Buyer"},
                           "Delivered Duty Paid (DDP)": {"Export Packaging": "Seller", "Loading Charges": "Seller",
                                                   "Delivery to Port/Place": "Seller",
                                                   "Export Duty, Taxes and Customs Clearance": "Seller",
                                                   "Origin Handling Terminal Charges": "Seller",
                                                   "Loading on Carriage": "Seller", "Freight Charges": "Seller",
                                                   "Insurance": "Seller (Negotiable)", "Destination Terminal Handling Charges": "Seller",
                                                   "Delivery To Destination": "Seller", "Unloading At Destination": "Buyer",
                                                   "Import Duty, Taxes and Customs Clearance": "Seller"}}}
